<a href="https://colab.research.google.com/github/kurotiyamitali-dotcom/Python-basic-project/blob/main/task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.random.randint(10, 101, (5, 6))

print(a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)

[[72 92 88 30 72 57]
 [53 38 75 60 61 65]
 [30 22 48 59 83 83]
 [61 53 72 57 37 72]
 [61 87 42 35 73 16]]
Shape: (5, 6)
Size: 30
Data Type: int64


In [2]:
import numpy as np

a = np.random.randint(1, 51, 20)

print(a)
print("Minimum:", np.min(a))
print("Index:", np.argmin(a))
print("Maximum:", np.max(a))
print("Index:", np.argmax(a))
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Std Dev:", np.std(a))

[ 7 19  8 46 36 30 29 24 10 27 33 26 34 45 43 27 17  5 45 41]
Minimum: 5
Index: 17
Maximum: 46
Index: 3
Sum: 552
Mean: 27.6
Std Dev: 12.924395537122809


In [3]:
import numpy as np

a = np.random.randint(20, 81, (4, 5))

print(a)
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Std Dev:", np.std(a))
print("Row Sum:", np.sum(a, axis=1))
print("Column Sum:", np.sum(a, axis=0))

[[36 65 80 24 65]
 [40 73 40 23 63]
 [47 62 65 66 66]
 [44 22 33 28 73]]
Minimum: 22
Maximum: 80
Sum: 1015
Mean: 50.75
Std Dev: 18.506417805723505
Row Sum: [270 239 306 200]
Column Sum: [167 222 218 141 267]


In [4]:
import numpy as np

a = np.arange(1, 25)

print(a)

print(a.reshape(4, 6))
print(a.reshape(3, 8))
print(a.reshape(2, 3, 4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [5]:
import numpy as np

arr = np.array([[10,20,30,40],
                [50,60,70,80],
                [90,100,110,120]])

print("First Row:", arr[0])
print("Last Column:", arr[:,3])
print("Center 2x2:")
print(arr[1:3,1:3])
print("Even Numbers:")
print(arr[arr % 2 == 0])

First Row: [10 20 30 40]
Last Column: [ 40  80 120]
Center 2x2:
[[ 60  70]
 [100 110]]
Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [6]:
import numpy as np

a = np.random.randint(1,101,(5,5))

print(a)
print("Diagonal:", np.diag(a))
print("Greater than 50:", a[a>50])

a[a<30] = 0

print("Modified Array:")
print(a)

[[81 46  8 89 45]
 [63 73 43 22 68]
 [50 69 87 65 47]
 [81 62 33 15 34]
 [97 78 64 34 87]]
Diagonal: [81 73 87 15 87]
Greater than 50: [81 89 63 73 68 69 87 65 81 62 97 78 64 87]
Modified Array:
[[81 46  0 89 45]
 [63 73 43  0 68]
 [50 69 87 65 47]
 [81 62 33  0 34]
 [97 78 64 34 87]]


In [7]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Power:", a**b)
print("Modulo:", a%b)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [     10     400   27000 2560000]
Modulo: [0 0 0 0]


In [8]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Element-wise:")
print(A*B)

print("Matrix Multiplication:")
print(A@B)

Element-wise:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [9]:
import numpy as np

a = np.random.randn(6,6)

print(a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data Type:", a.dtype)
print("Max Index:", np.argmax(a))
print("Min Value:", np.min(a))

print("Top Left 3x3:")
print(a[:3,:3])

a = np.abs(a)

print("Mean:", np.mean(a))

[[-7.17130818e-01  9.07833669e-02 -1.00351890e+00  4.54077570e-01
  -1.51158093e+00 -1.26693320e-01]
 [-2.30263987e-01 -1.35835145e+00 -4.55287133e-01  1.55050585e-03
  -6.68359544e-02  1.21343949e+00]
 [-1.89092857e+00  1.29836344e+00  1.08657486e+00 -1.54805235e+00
  -1.17598595e+00  4.70491564e-01]
 [ 1.80569934e+00  9.34465725e-01  6.53321161e-01  1.45161198e+00
   5.81635114e-01  2.40356910e-01]
 [-5.26266598e-02 -1.89803029e+00  2.77043647e+00  8.20370813e-01
  -6.78077117e-01  2.00319927e-01]
 [ 9.10418044e-01  8.36206955e-01 -4.40896769e-01  1.89772954e-01
  -1.14135967e+00 -4.96827179e-01]]
Shape: (6, 6)
Size: 36
Data Type: float64
Max Index: 26
Min Value: -1.8980302945977274
Top Left 3x3:
[[-0.71713082  0.09078337 -1.0035189 ]
 [-0.23026399 -1.35835145 -0.45528713]
 [-1.89092857  1.29836344  1.08657486]]
Mean: 0.8556206453159481


In [10]:
import numpy as np

marks = np.random.randint(30,101,(10,5))

print("Marks:")
print(marks)

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)

print("Total:", total)
print("Average:", average)

print("Highest Total Student:", np.argmax(total))
print("Lowest Total Student:", np.argmin(total))

print("Class Mean:", np.mean(marks))
print("Class Std Dev:", np.std(marks))

print("Top 3 Students Marks:")
print(marks[:3])

Marks:
[[33 32 79 80 39]
 [83 66 74 63 71]
 [35 96 42 74 36]
 [97 76 92 51 79]
 [34 76 58 65 97]
 [75 60 30 92 75]
 [83 64 43 94 90]
 [57 77 50 40 99]
 [71 63 42 39 74]
 [76 74 56 37 46]]
Total: [263 357 283 395 330 332 374 323 289 289]
Average: [52.6 71.4 56.6 79.  66.  66.4 74.8 64.6 57.8 57.8]
Highest Total Student: 3
Lowest Total Student: 0
Class Mean: 64.7
Class Std Dev: 20.399264692630467
Top 3 Students Marks:
[[33 32 79 80 39]
 [83 66 74 63 71]
 [35 96 42 74 36]]
