<a href="https://colab.research.google.com/github/kurotiyamitali-dotcom/Python-basic-project/blob/main/task13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Data Type:", arr1.dtype)

print("\n2D Array:")
print(arr2)
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)

1D Array:
[10 20 30 40 50]
Shape: (5,)
Data Type: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [32]:
import numpy as np

a = np.zeros(8)
b = np.ones((4,4))
c = np.zeros((3,3))

print("1D Array of Zeros:")
print(a)

print("\n4x4 Array of Ones:")
print(b)

print("\n3x3 Matrix of Zeros:")
print(c)

1D Array of Zeros:
[0. 0. 0. 0. 0. 0. 0. 0.]

4x4 Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
import numpy as np

a = np.arange(0,21,1)
b = np.arange(10,51,2)
c = np.arange(5,101,5)

print("0 to 20:")
print(a)

print("\nEven Numbers 10 to 50:")
print(b)

print("\n5 to 100 Step 5:")
print(c)

0 to 20:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Even Numbers 10 to 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

5 to 100 Step 5:
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [24]:
import numpy as np

a = np.linspace(0,5,10)
b = np.linspace(-10,10,15)

print("0 to 5:")
print(a)
print("Length:", len(a))

print("\n-10 to 10:")
print(b)
print("Length:", len(b))

0 to 5:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

-10 to 10:
[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [25]:
import numpy as np

a = np.random.rand(10)
b = np.random.randn(3,3)
c = np.random.randint(10,51,(4,5))

print("Random Numbers (0-1):")
print(a)

print("\nStandard Normal Matrix:")
print(b)

print("\nRandom Integers (10-50):")
print(c)

Random Numbers (0-1):
[0.5681811  0.52368103 0.54504845 0.10303112 0.89155719 0.67712555
 0.30547311 0.47996198 0.20946536 0.34451208]

Standard Normal Matrix:
[[ 0.22488604  1.71137326  1.5120526 ]
 [-0.4658761   0.12660312 -0.69918921]
 [-1.23138409  0.29458368  0.66225802]]

Random Integers (10-50):
[[33 42 25 41 41]
 [40 44 48 38 27]
 [50 14 48 26 47]
 [10 44 24 12 20]]


In [26]:
import numpy as np

v1 = np.array([2,4,6,8])
v2 = np.array([1,3,5,7])

print("Addition:")
print(v1 + v2)

print("\nSubtraction:")
print(v1 - v2)

print("\nElement-wise Multiplication:")
print(v1 * v2)

print("\nDot Product:")
print(np.dot(v1,v2))

Addition:
[ 3  7 11 15]

Subtraction:
[1 1 1 1]

Element-wise Multiplication:
[ 2 12 30 56]

Dot Product:
100


In [27]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Matrix Addition:")
print(A+B)

print("\nMatrix Multiplication:")
print(A @ B)

print("\nElement-wise Multiplication:")
print(A*B)

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [28]:
import numpy as np

A = np.random.randint(1,101,(4,4))

print("Matrix:")
print(A)

print("\nShape:", A.shape)
print("Dimension:", A.ndim)
print("Size:", A.size)
print("Data Type:", A.dtype)
print("Minimum:", A.min())
print("Maximum:", A.max())

Matrix:
[[74 46 84 62]
 [19 42 69  9]
 [42 27 78 15]
 [36 30 90 98]]

Shape: (4, 4)
Dimension: 2
Size: 16
Data Type: int64
Minimum: 9
Maximum: 98


In [29]:
import numpy as np

A = np.random.randint(1,51,20)

print("Original Array:")
print(A)

B = A.reshape(4,5)

print("\nReshaped Matrix:")
print(B)

print("\nSum:", np.sum(B))
print("Mean:", np.mean(B))
print("Standard Deviation:", np.std(B))

print("\nMaximum in Each Row:")
print(np.max(B, axis=1))

Original Array:
[27 46 31 17 41 33 29 42 38 21 26  1 44 24 43 42 13 38 32 21]

Reshaped Matrix:
[[27 46 31 17 41]
 [33 29 42 38 21]
 [26  1 44 24 43]
 [42 13 38 32 21]]

Sum: 609
Mean: 30.45
Standard Deviation: 11.599461194383125

Maximum in Each Row:
[46 42 44 42]


In [30]:
import numpy as np

try:
    n = int(input("How many numbers do you want to generate? "))

    arr = np.random.randint(10,101,n)

    print("\nGenerated Array:")
    print(arr)

    print("\nMean:", np.mean(arr))
    print("Median:", np.median(arr))
    print("Standard Deviation:", np.std(arr))
    print("Minimum:", np.min(arr))
    print("Maximum:", np.max(arr))

    if n % 2 == 0:
        rows = 2
        cols = n // 2
        matrix = arr.reshape(rows, cols)

        print("\n2D Array:")
        print(matrix)

        print("\nRow-wise Sum:")
        print(np.sum(matrix, axis=1))
    else:
        print("\nCannot reshape into a 2D array because the number of elements is odd.")

except ValueError:
    print("Please enter a valid integer.")

How many numbers do you want to generate? 6

Generated Array:
[77 30 49 31 99 63]

Mean: 58.166666666666664
Median: 56.0
Standard Deviation: 24.700989633795828
Minimum: 30
Maximum: 99

2D Array:
[[77 30 49]
 [31 99 63]]

Row-wise Sum:
[156 193]
